# Gestión de Datos

Parcial 1 
Univerisdad Javeriana  
August, 2022  
  
Dataset: StudentsPerformance_exam1

## **EDA StudentsPerformance_exam1**

### General

In [1]:
# Importing libraries

import numpy as np
import pandas as pd
from datetime import datetime

import matplotlib.pyplot as plt
import seaborn as sns

from pandas_profiling import ProfileReport

import pylev

%matplotlib inline

In [11]:
# Configuración de Panadas
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

In [12]:
# Carga de datos desde archivo CSV
students_performance_df = pd.read_csv('data/StudentsPerformance_exam1.csv',sep=",",header= 0)

In [13]:
# 1 ¿Qué tipo de variables tiene el dataset? Detalle el tipo de variable de cada columna.

In [14]:
# Vista inicial del dataFrame
students_performance_df.head()

gender race/ethnicity parental level of education         lunch  \
0  non-binary        group B           bachelor's degree      standard   
1      female        group C                some college      standard   
2      female        group B             master's degree      standard   
3        male        group A          associate's degree  free/reduced   
4        male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none        72.0           72.0            NaN  
1               completed        69.0           90.0           88.0  
2                    none        90.0           95.0           93.0  
3                    none         NaN           57.0           44.0  
4                    none        76.0           78.0           75.0

In [15]:
# Dimensiones del DataFrame junto con el tipo de datos de las variables
students_performance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   gender                       953 non-null    object 
 1   race/ethnicity               955 non-null    object 
 2   parental level of education  940 non-null    object 
 3   lunch                        946 non-null    object 
 4   test preparation course      959 non-null    object 
 5   math score                   949 non-null    float64
 6   reading score                952 non-null    float64
 7   writing score                951 non-null    float64
dtypes: float64(3), object(5)
memory usage: 62.6+ KB


In [30]:
students_performance_df.dtypes

gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                     float64
reading score                  float64
writing score                  float64
dtype: object

In [16]:
# 2. ¿Qué tipo de problemas de calidad de datos logra identificar? 
# Defina e implemente las estrategias de limpieza de datos que correspondan.

### Calidad de los Datos

In [17]:
# Datos unicos de la columna gender
students_performance_df['gender'].unique()

array(['non-binary', 'female', 'male', nan], dtype=object)

In [18]:
# Datos unicos de la columna race/ethnicity
students_performance_df['race/ethnicity'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E', nan],
      dtype=object)

In [41]:
# Datos unicos de la columna parental level of education
students_performance_df['parental level of education'].unique()

array(["bachelor's degree", 'some high school', "master's degree",
       "associate's degree", 'high school', nan], dtype=object)

In [20]:
# Datos unicos de la columna parental lunch
students_performance_df['lunch'].unique()

array(['standard', 'free/reduced', nan], dtype=object)

In [22]:
# Datos unicos de la columna test preparation course 
students_performance_df['test preparation course'].unique()

array(['none', 'completed', nan], dtype=object)

In [49]:
# Datos nulos por variable
students_performance_df.isnull().sum()

gender                         47
race/ethnicity                 45
parental level of education    60
lunch                          54
test preparation course        41
math score                     51
reading score                  48
writing score                  49
dtype: int64

In [56]:
# Datos unicos de la columna math score
students_performance_df['math score'].unique()

array([ 72.,  69.,  90.,  nan,  76.,  71.,  88.,  40.,  64.,  38.,  58.,
        65.,  78.,  50.,  18.,  46.,  54.,  66.,  44.,  74.,  73.,  67.,
        63.,  56.,  97.,  81.,  75.,  55.,  53.,  59.,  57.,  82.,  77.,
        33.,  79.,  39.,  62.,  45.,  60.,  41.,  61.,  49.,  30.,  47.,
        42.,  27.,  43.,  68.,  85.,  98.,  87.,  52.,  70.,  51.,  99.,
        84.,  91.,  83.,  89.,  22., 100.,  96.,  94.,  80.,  48.,  35.,
        34.,  86.,  92.,  37.,  28.,  24.,  26.,  95.,  36.,  29.,  32.,
        93.,  19.,  23.,   8.])

In [26]:
# Datos unicos de la columna reading score
students_performance_df['reading score'].unique()

array([ 72.,  90.,  95.,  57.,  78.,  83.,  43.,  64.,  60.,  54.,  52.,
        81.,  53.,  75.,  89.,  32.,  42.,  58.,  69.,  73.,  71.,  74.,
        70.,  65.,  87.,  56.,  61.,  84.,  55.,  44.,  nan,  41.,  85.,
        59.,  17.,  80.,  37.,  51.,  49.,  26.,  68.,  45.,  39.,  86.,
        34.,  79.,  66.,  67.,  91., 100.,  63.,  76.,  77.,  82.,  92.,
        93.,  62.,  88.,  50.,  28.,  48.,  46.,  23.,  38.,  94.,  97.,
        99.,  31.,  47.,  96.,  24.,  29.,  40.])

In [28]:
# Datos unicos de la columna gender
students_performance_df['writing score'].unique()

array([ nan,  88.,  93.,  44.,  75.,  78.,  92.,  39.,  67.,  50.,  52.,
        43.,  73.,  70.,  58.,  86.,  28.,  46.,  61.,  63.,  53.,  80.,
        72.,  55.,  65.,  74.,  38.,  82.,  79.,  83.,  59.,  57.,  54.,
        68.,  66.,  62.,  76.,  48.,  42.,  87.,  49.,  10.,  34.,  71.,
        37.,  56.,  41.,  22.,  81.,  45.,  36.,  89.,  47.,  90., 100.,
        64.,  98.,  51.,  40.,  84.,  69.,  33.,  60.,  85.,  91.,  77.,
        27.,  94.,  95.,  19.,  35.,  32.,  96.,  97.,  99.,  15.,  30.,
        23.])

In [29]:
# Al validar los datos se encuentran por cada variable:
# gender:                     Se encuentran datos nulos, es decir la columna presenta falta de completitud
#race/ethnicity:              Se encuentran datos nulos, es decir la columna presenta falta de completitud, 
#                             por otro lado los grupos no indican cual es la race/ethnicity es decir variable
#                             no tiene datos precisos ni relevantes.
#parental level of education: Se encuentran datos nulos, es decir la columna presenta falta de completitud,
#                             por otro lado, se representa de diferentes formas el mismo dato lo cual indica
#                             que los datos de la variable no son conformes.
#lunch:                       Se encuentran datos nulos, es decir la columna presenta falta de completitud
#test preparation course:     Se encuentran datos nulos, es decir la columna presenta falta de completitud
#math score:                  Se encuentran datos nulos, es decir la columna presenta falta de completitud
#reading score:               Se encuentran datos nulos, es decir la columna presenta falta de completitud
#writing score:               Se encuentran datos nulos, es decir la columna presenta falta de completitud

In [42]:
#Se crea un diccionario para la variable parental education
level_education_list = ["bachelor's degree", 'college', "master's degree",
       "associate's degree", 'high school']

In [47]:
students_performance_df.loc[~students_performance_df["parental level of education"].isin(level_education_list), "parental level of education"].unique()

array(['some high school', nan], dtype=object)

In [46]:
students_performance_df["parental level of education"] = students_performance_df["parental level of education"].replace(["some college","college"],['some high school',"high school"])

In [64]:
#Asignar 0 a las calificaciones con datos nulos
students_performance_df["math score"] = students_performance_df["math score"].fillna(0)
students_performance_df["reading score"] = students_performance_df["reading score"].fillna(0)
students_performance_df["writing score"] = students_performance_df["writing score"].fillna(0)

In [78]:
#3. ¿En qué asignatura en promedio los estudiantes obtuvieron un mejor puntaje? 
#¿Hay evidencia de algún sesgo en la distribución de dichos puntajes?
students_performance_df[['math score', 'reading score',"writing score"]].mean()

math score       62.806
reading score    65.933
writing score    64.841
dtype: float64

In [72]:
#El mejor promedio se obtuvo en la materia de reading

In [77]:
#4. ¿Existe alguna correlación entre los puntajes obtenidos en las tres asignaturas?
students_performance_df[['math score', 'reading score',"writing score"]].corr('spearman')

math score  reading score  writing score
math score        1.00000       0.685630       0.637280
reading score     0.68563       1.000000       0.808399
writing score     0.63728       0.808399       1.000000

In [ ]:
#Se encuentra una alta correlación entre las variables reading score y writing score

In [86]:
#5. ¿Hay alguna diferencia observable en los puntajes de la asignatura de matemáticas entre géneros? 
#¿Qué género obtuvo en promedio los mejorespuntajes?
students_performance_df.groupby(['gender']).sum()

math score  reading score  writing score
gender                                              
female         25695.0        28964.0        29488.0
male           24995.0        24329.0        23164.0
non-binary      9153.0         9710.0         9187.0

In [88]:
#La diferencia que salta a la vista es que el genero no-binary obtuvo menor puntaje y 
#quienes obtuvieron mayor puntaje fue el genero female

In [ ]:
#6 ¿Qué nivel de escolaridad tienen los padres de los estudiantes que obtuvieron
#un puntaje por encima del percentil 85 en la asignatura de escritura? ¿Cómo se
#distribuye la escolaridad entre esta población?.

In [89]:
students_performance_df.describe()

math score  reading score  writing score
count  1000.000000    1000.000000    1000.000000
mean     62.806000      65.933000      64.841000
std      20.668516      20.517443      20.853119
min       0.000000       0.000000       0.000000
25%      54.000000      58.000000      55.000000
50%      65.000000      69.000000      68.000000
75%      76.000000      79.000000      78.000000
max     100.000000     100.000000     100.000000

In [102]:
percentile_85 = np.percentile(students_performance_df["writing score"], 85)
percentile_85

83.0

In [ ]:
students_performance_df_2 = students_performance_df[students_performance_df["writing score"] > 83]
students_performance_df_2.unique()

gender race/ethnicity parental level of education         lunch  \
1        female        group C            some high school      standard   
2        female        group B             master's degree      standard   
6    non-binary        group B            some high school      standard   
16         male        group C                 high school      standard   
54       female        group C            some high school  free/reduced   
..          ...            ...                         ...           ...   
979      female        group C          associate's degree      standard   
982        male        group B            some high school      standard   
983      female        group A            some high school      standard   
995      female        group E             master's degree      standard   
999      female        group D            some high school  free/reduced   

    test preparation course  math score  reading score  writing score  
1                 completed        69.0           90.0           88.0  
2                      none        90.0           95.0           93.0  
6                 completed        88.0           95.0           92.0  
16                     none        88.0           89.0           86.0  
54                completed        71.0           84.0           87.0  
..                      ...         ...            ...            ...  
979                    none        91.0           95.0           94.0  
982               completed        79.0           85.0           86.0  
983               completed        78.0           87.0           91.0  
995               completed        88.0            0.0           95.0  
999                    none        77.0           86.0           86.0  

[146 rows x 8 columns]

In [101]:
# Datos unicos de la columna parental level of education
students_performance_df_2['parental level of education'].unique()

array(['some high school', "master's degree", 'high school',
       "associate's degree", nan, "bachelor's degree"], dtype=object)

In [ ]:
#7 ¿Qué porcentaje de los estudiantes obtuvieron puntajes iguales o superiores a
#90 en las tres asignaturas? De estos estudiantes¿que porcentaje estudió para los exámenes?